name: lefthook
version: 1.1.1
description: Fast and powerful Git hooks manager for any type of projects.
homepage: https://github.com/drt-pkgz/lefthook
environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  system_info: ^1.0.1
  archive: ^3.3.1
  cli_util: ^0.3.5
executables:
  lefthook: lefthook
